# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9027
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    # -   id: roxygenize
    #     # roxygen requires loading pkg -> add dependencies from DESCRIPTION
    #     additional_dependencies:
    #     -    assertthat
    #     -    cli
    #     -    httr
    #     -    git2r
    #     -    miniUI
    #     -    openai
    #     -    purrr
    #     -    rlang
    #     -    rstudioapi
    #     -    shiny
    #     -    skimr
    #     -    stats
    #     -    usethis
    #-   id: use-tidy-description
    #    args: [--warn_only]
    -   id: lintr
        args: [--warn_only]
        verbose: true
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
        args: [--allow_private_imports --warn_only]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=2000']
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit files that may contain sensitive info
        language: fail
        files: '\.(Rhistory|RData|Rds|rds|Renviron|Rprofile|env)$'
        # `exclude: <regex>` to allow committing specific files

ci:
    autoupdate_schedule: monthly
