library(gpttools)
crawl("https://wesmckinney.com/book")
crawl("https://jakevdp.github.io/PythonDataScienceHandbook/")
crawl("https://tidyverse.org")
crawl("https://tidymodels.org", aggressive = TRUE)
crawl("https://parsnip.tidymodels.org")
crawl("https://recipes.tidymodels.org")
crawl("https://tmwr.org")
crawl("https://posit.co", aggressive = TRUE)
